### ISSUE TITLE
[Suggestion][Reddit HNC] Different colors per time interval

### ISSUE THREAD

**Issue by ghost** [monk-time/userscripts#1]
Your fork is great! Seems faster for some reason too.

My suggestion is: choose 3 or more colors to help us find new comments we already read before. This is only useful for hot threads when there's so much going when that if you refresh you have to keep clearing/changing the time.

Example:

- #89c4f4: 45 minutes
- #4183d7: 20 minutes
- #19b5fe: 5 minutes

Bad idea?

**Comment by monk-time** [comment]
Hi!

I have played a bit with your idea and added different shades to *unread* comments based on their recency in 9ef0c19aae878b2f066dbd9100a7c48973453f9f, but then I noticed that I missed the part about 'new comments we already read before'. Reading comprehension is hard. 

Can you explain your use case a bit more? Do you mean when you refresh before reading a thread to the end? So in your example, if the last visit was an hour ago, nothing will change, right?

I think in those cases I usually open subthreads in additional tabs and refresh those. My idea was to keep the amount of visual clutter to the minimum, I'm afraid highlighting old comments would get too noisy.

**Comment by ghost** [comment]
> Can you explain your use case a bit more?

When threads are getting 5+ comments per minute and you refresh the page it's not uncommon for the page to move all around (or in sub threads that you can open in a new tab, like you've mentioned), especially if you're using RES. The colors make it easier to navigate around, kinda like a heatmap. The way you implemented https://github.com/monk-time/userscripts/commit/9ef0c19aae878b2f066dbd9100a7c48973453f9f works great already and solves this issue 👍

P.S. `www|[a-z]{2}` doesn't catch old.reddit.com, so maybe you could add `|old`

**Comment by monk-time** [comment]
Well, I'm glad you liked it! And thanks for that heads-up about old.reddit.com, I will merge the branch and fix it as soon as I can.
